name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cpp-linter/cpp-linter-action@v2
      with:
        style: 'Google'
        lines-changed-only: 'false'

    - name: Install dependency
      run: sudo apt-get install lcov
    - name: 1. Compile
      run: make build
    - name: 2. Run executable
      run: ./main
    - name: 3. Generate report
      run: make report
    - name: Update lcov report
      if: github.ref == 'refs/heads/master'
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout -b coverage
        git add --all
        git commit -m "Update lcov report"
        git push -f origin coverage
